/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL slug for the page (e.g., "about-us")
   */
  slug: string;
  /**
   * Show this page in the main navigation menu
   */
  showInMenu?: boolean | null;
  /**
   * Order in the menu (lower numbers appear first)
   */
  menuOrder?: number | null;
  /**
   * Custom label for the main menu link (uses page title if blank)
   */
  menuLabel?: string | null;
  /**
   * Optional inline CSS rules applied to this menu item (e.g. "color: #fff; background-color: #ccc;"). Plain CSS declarations only — no selectors or classes.
   */
  menuItemStyle?: string | null;
  /**
   * Show this page as a call-to-action in the header toolbar (above main menu)
   */
  showInToolbar?: boolean | null;
  /**
   * Custom label for toolbar (uses page title if blank)
   */
  toolbarLabel?: string | null;
  /**
   * Order in the toolbar (lower numbers appear first)
   */
  toolbarOrder?: number | null;
  /**
   * Override the main menu for this page. When enabled, only the menu items configured below are shown (in this order), instead of the default menu. If none are added, no page menu items appear.
   */
  overrideMainMenu?: boolean | null;
  /**
   * The main menu links shown on this page. Drag to reorder — items appear in this order. Each link can point to any page and use its own label.
   */
  menuItems?:
    | {
        /**
         * The page this menu link points to.
         */
        page: number | Page;
        /**
         * Custom label for this link (uses the page's menu label or title if blank).
         */
        label?: string | null;
        /**
         * Optional anchor on the target page to jump to — the id of an Anchor block there (e.g. "about"). Leave blank to link to the top of the page.
         */
        anchor?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Add and arrange content blocks for this page
   */
  content?:
    | (
        | {
            /**
             * The id for this spot on the page. Link to it from elsewhere with #<id> — e.g. set "about" here, then link to "https://mysite.com/#about". Use lowercase letters, numbers and hyphens; no spaces.
             */
            anchorId: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'anchor';
          }
        | {
            /**
             * Calendly URL (e.g. "https://calendly.com/<username>/<event>?hide_event_type_details=1&hide_gdpr_banner=1")
             */
            url: string;
            /**
             * Inline CSS style for the Calendly widget container
             */
            style?: string | null;
            /**
             * Optional text column shown next to the embed (use headings for the title). Leave empty for an embed-only, full-width layout.
             */
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Side the text column sits on (the embed takes the other side)
             */
            textPosition?: ('left' | 'right') | null;
            /**
             * Width of the text column as a percentage (the embed takes the rest)
             */
            textPercentage?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calendlyEmbed';
          }
        | {
            /**
             * Add content cells to the grid
             */
            cells: {
              /**
               * What this cell holds. A stat counter shows a large number that counts up from zero when it scrolls into view.
               */
              elementType?: ('richText' | 'counter') | null;
              /**
               * Cell content
               */
              content?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              /**
               * Truncate this cell with a fade-out and a "Lees meer" button that expands the full content.
               */
              collapsedByDefault?: boolean | null;
              /**
               * How many lines to show before fading out.
               */
              collapsedLines?: ('5' | '8' | '12' | '16' | '20') | null;
              /**
               * The target number to count up to.
               */
              counterValue?: number | null;
              /**
               * Show the infinity symbol (∞) instead of a number. The counter still animates up, then cross-fades to ∞.
               */
              counterInfinite?: boolean | null;
              /**
               * Append a "+" after the number (e.g. "8+").
               */
              counterShowPlus?: boolean | null;
              /**
               * Caption shown beneath the number (e.g. "Jaren ervaring").
               */
              counterLabel?: string | null;
              /**
               * Color of the number (the label stays in the muted body color).
               */
              counterColor?: string | null;
              id?: string | null;
            }[];
            /**
             * Number of columns on desktop
             */
            numberOfColumns?: ('2' | '3' | '4' | '5') | null;
            /**
             * Horizontal text alignment within cells
             */
            horizontalAlignment?: ('left' | 'center' | 'right') | null;
            /**
             * Vertical alignment of cells
             */
            verticalAlignment?: ('top' | 'center' | 'bottom') | null;
            /**
             * Show a small 01/02/… index and hairline rule above each cell — reads like a magazine spread. Best on 2–4 column left-aligned grids.
             */
            editorialNumbers?: boolean | null;
            /**
             * Wrap each cell in a translucent card with padding.
             */
            renderAsCards?: boolean | null;
            /**
             * Card background tone.
             */
            cardBackground?: ('lighten' | 'darken') | null;
            /**
             * Apply rounded corners to each card.
             */
            cardRoundedCorners?: boolean | null;
            /**
             * Stretch every cell in a row to match the tallest one. Most visible when cells render as cards.
             */
            equalRowHeights?: boolean | null;
            /**
             * Background color for the whole grid (adds padding around the cells).
             */
            backgroundColor?: string | null;
            /**
             * Background color stretches horizontally across the full page width (cells stay within the container).
             */
            fullBleed?: boolean | null;
            /**
             * Draw subtle hairline rules between cells, like the columns of a magazine spread.
             */
            cellDividers?: boolean | null;
            /**
             * Color of the dividing lines (rendered at low opacity).
             */
            cellDividerColor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentGrid';
          }
        | {
            /**
             * Background image for the hero section
             */
            backgroundImage?: (number | null) | Media;
            /**
             * Vertical focal point in % (0 = top, 50 = center, 100 = bottom)
             */
            focalPointY?: number | null;
            /**
             * Center the background image horizontally. Uncheck to set a custom horizontal focal point.
             */
            centered?: boolean | null;
            /**
             * Horizontal focal point in % (0 = left, 50 = center, 100 = right)
             */
            focalPointX?: number | null;
            /**
             * Apply a dark or light overlay on the background image to improve text readability
             */
            overlay?: ('none' | 'darken' | 'lighten') | null;
            /**
             * Overlay strength in % (0 = transparent, 100 = fully opaque)
             */
            overlayStrength?: number | null;
            /**
             * Text alignment within the hero
             */
            alignment?: ('left' | 'center' | 'right') | null;
            /**
             * Height of the hero section
             */
            height?: ('small' | 'medium' | 'large' | 'xl' | 'xxl' | 'xxxl') | null;
            /**
             * Add and arrange content within the hero
             */
            content?:
              | (
                  | {
                      /**
                       * The main headline text. Select text to color individual words or phrases.
                       */
                      text: {
                        root: {
                          type: string;
                          children: {
                            type: any;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      };
                      /**
                       * Heading level — matches the WYSIWYG heading sizes.
                       */
                      fontSize: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'heroHeadline';
                    }
                  | {
                      /**
                       * Supporting text below the headline. Select text to color individual words or phrases.
                       */
                      text: {
                        root: {
                          type: string;
                          children: {
                            type: any;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      };
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'heroSubheadline';
                    }
                  | {
                      content: {
                        root: {
                          type: string;
                          children: {
                            type: any;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      };
                      /**
                       * Content width and alignment within the hero
                       */
                      layout?: ('full' | 'left' | 'right') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'heroRichText';
                    }
                  | {
                      /**
                       * Static text shown before the rotating words (e.g. "We help you")
                       */
                      prefix?: string | null;
                      /**
                       * Words that cycle one after the other (minimum 2)
                       */
                      rotatingWords: {
                        word: string;
                        id?: string | null;
                      }[];
                      /**
                       * Optional static text shown after the rotating words
                       */
                      suffix?: string | null;
                      /**
                       * How long each word stays on screen, in milliseconds
                       */
                      intervalMs?: number | null;
                      /**
                       * Heading level — matches the WYSIWYG heading sizes.
                       */
                      fontSize: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'heroRotatingHeadline';
                    }
                  | {
                      /**
                       * Call-to-action buttons (max 4)
                       */
                      links: {
                        label: string;
                        /**
                         * URL or path (e.g., /contact or https://example.com)
                         */
                        url: string;
                        variant?: ('solid' | 'outline' | 'ghost') | null;
                        id?: string | null;
                      }[];
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'heroCta';
                    }
                  | {
                      /**
                       * Height of the spacer within the hero
                       */
                      height: 'xs' | 'small' | 'medium' | 'large' | 'xl';
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'heroSpacer';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Add logo images to scroll in the marquee (minimum 3)
             */
            logos: {
              /**
               * Logo image (transparent PNG or SVG recommended)
               */
              image: number | Media;
              /**
               * Alt text for the logo (overrides media alt text)
               */
              alt?: string | null;
              id?: string | null;
            }[];
            /**
             * Uniform height of the logos
             */
            logoSize?: ('small' | 'medium' | 'large') | null;
            /**
             * Scrolling speed of the marquee
             */
            speed?: ('slow' | 'medium' | 'fast') | null;
            /**
             * Pause the marquee when the user hovers over it
             */
            pauseOnHover?: boolean | null;
            /**
             * Show logos in muted grayscale, revealing full color on hover. Disable to show logos in full color always.
             */
            colorizeOnHover?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoMarquee';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Body is regular prose. Hero is for panel/overlay taglines where the first paragraph should read as a display lede. Long-form applies magazine-style reading measure and a drop cap on the first paragraph.
             */
            variant?: ('body' | 'hero' | 'longForm') | null;
            width?: ('1/4' | '1/3' | 'half' | '2/3' | '3/4' | 'full') | null;
            /**
             * When enabled, the block will be rendered with absolute positioning inside a relative wrapper.
             */
            renderFloating?: boolean | null;
            /**
             * CSS value for vertical offset, e.g. "20px", "3em", "-10px"
             */
            floatingOffset?: string | null;
            /**
             * Vertical margin above and below the block
             */
            margin?: ('none' | 'small' | 'medium' | 'large') | null;
            /**
             * Background color for this block
             */
            backgroundColor?: string | null;
            /**
             * Color stretches horizontally across the full page width (content stays within container)
             */
            fullBleed?: boolean | null;
            /**
             * Lay a dark overlay over the background (like the hero) to lift text contrast — handy with the checkered pattern.
             */
            darken?: boolean | null;
            /**
             * Overlay strength in % (0 = transparent, 100 = fully opaque)
             */
            darkenStrength?: number | null;
            /**
             * Apply rounded corners to the block
             */
            roundedCorners?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Static text shown before the rotating words (e.g. "We help you")
             */
            prefix?: string | null;
            /**
             * Words that cycle one after the other (minimum 2)
             */
            rotatingWords: {
              word: string;
              id?: string | null;
            }[];
            /**
             * Optional static text shown after the rotating words
             */
            suffix?: string | null;
            /**
             * Text alignment
             */
            alignment?: ('left' | 'center' | 'right') | null;
            /**
             * How long each word stays on screen, in milliseconds
             */
            intervalMs?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rotatingHeadline';
          }
        | {
            /**
             * The height of the spacer
             */
            height: 'xxxs' | 'xxs' | 'xs' | 'small' | 'medium' | 'large' | 'xl' | 'xxl' | 'xxxl';
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer';
          }
        | {
            /**
             * Title and description text (use headings for the title)
             */
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Call-to-action buttons
             */
            buttons?:
              | {
                  /**
                   * Button text
                   */
                  caption: string;
                  /**
                   * URL or path (e.g., /contact or https://example.com)
                   */
                  link: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Choose between image or video for the visual element
             */
            mediaType?: ('image' | 'video') | null;
            /**
             * The image to display
             */
            image?: (number | null) | Media;
            /**
             * Horizontal focal point in % (0 = left, 50 = center, 100 = right)
             */
            focalPointX?: number | null;
            /**
             * Vertical focal point in % (0 = top, 50 = center, 100 = bottom)
             */
            focalPointY?: number | null;
            /**
             * Vimeo video ID (e.g., "123456789" from vimeo.com/123456789)
             */
            vimeoId?: string | null;
            /**
             * Poster image shown before the video plays
             */
            videoPoster?: (number | null) | Media;
            /**
             * Call-to-action text displayed over the video poster
             */
            videoCtaCaption?: string | null;
            /**
             * Position of the media relative to the text
             */
            imagePosition?: ('left' | 'right') | null;
            /**
             * Width percentage of the media section (20-80%)
             */
            imagePercentage?: number | null;
            /**
             * How to size the image: fixed aspect ratio or natural dimensions
             */
            imageSizingMode?: ('ratio' | 'natural') | null;
            /**
             * Aspect ratio of the image (width/height)
             */
            imageRatio?:
              | ('2/3' | '3/4' | '4/5' | '5/6' | '9/10' | '1/1' | '10/9' | '6/5' | '5/4' | '4/3' | '3/2')
              | null;
            /**
             * Vertical margin above and below the image
             */
            imageVerticalMargin?: ('none' | 'small' | 'medium' | 'large') | null;
            /**
             * Horizontal margin on left and right of the image
             */
            imageHorizontalMargin?: ('none' | 'small' | 'medium' | 'large') | null;
            /**
             * Maximum size of the image (maintains natural aspect ratio)
             */
            imageSize?:
              | (
                  | 'tiny-icon'
                  | 'small-icon'
                  | 'icon'
                  | 'large-icon'
                  | 'tiny'
                  | 'small'
                  | 'medium'
                  | 'large'
                  | 'xlarge'
                  | 'huge'
                )
              | null;
            /**
             * Margin around the text container (centered within text section)
             */
            textContainerMargin?: ('none' | 'small' | 'medium' | 'large') | null;
            /**
             * Background color for this block
             */
            backgroundColor?: string | null;
            /**
             * Color stretches horizontally across the full page width (content stays within container)
             */
            fullBleed?: boolean | null;
            /**
             * Apply rounded corners to the entire block
             */
            roundedCorners?: boolean | null;
            /**
             * Text is collapsed to the height of the media with a fade effect. A "Lees meer" button expands it.
             */
            collapsedByDefault?: boolean | null;
            /**
             * If checked, numbered lists in this block start at 0 instead of 1
             */
            startNumberedListAtZero?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitTextImage';
          }
        | {
            /**
             * Add testimonials to display in the carousel
             */
            testimonials: {
              /**
               * The testimonial quote text
               */
              quote: string;
              /**
               * Name of the person giving the testimonial (e.g. "John Doe (Company)")
               */
              name: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            /**
             * Vimeo video ID (e.g., "123456789" from vimeo.com/123456789)
             */
            vimeoId: string;
            /**
             * Poster image shown before the video plays
             */
            posterImage: number | Media;
            /**
             * Call-to-action button text that appears over the poster image
             */
            ctaCaption?: string | null;
            /**
             * Width of the video player
             */
            width?: ('half' | '2/3' | '3/4' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
      )[]
    | null;
  /**
   * Search engine optimization settings
   */
  seo?: {
    /**
     * Meta description for search engines (recommended: 150-160 characters)
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility
   */
  alt?: string | null;
  /**
   * Optional caption to display below the image
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * User role for access control
   */
  role: 'admin' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  showInMenu?: T;
  menuOrder?: T;
  menuLabel?: T;
  menuItemStyle?: T;
  showInToolbar?: T;
  toolbarLabel?: T;
  toolbarOrder?: T;
  overrideMainMenu?: T;
  menuItems?:
    | T
    | {
        page?: T;
        label?: T;
        anchor?: T;
        id?: T;
      };
  content?:
    | T
    | {
        anchor?:
          | T
          | {
              anchorId?: T;
              id?: T;
              blockName?: T;
            };
        calendlyEmbed?:
          | T
          | {
              url?: T;
              style?: T;
              text?: T;
              textPosition?: T;
              textPercentage?: T;
              id?: T;
              blockName?: T;
            };
        contentGrid?:
          | T
          | {
              cells?:
                | T
                | {
                    elementType?: T;
                    content?: T;
                    collapsedByDefault?: T;
                    collapsedLines?: T;
                    counterValue?: T;
                    counterInfinite?: T;
                    counterShowPlus?: T;
                    counterLabel?: T;
                    counterColor?: T;
                    id?: T;
                  };
              numberOfColumns?: T;
              horizontalAlignment?: T;
              verticalAlignment?: T;
              editorialNumbers?: T;
              renderAsCards?: T;
              cardBackground?: T;
              cardRoundedCorners?: T;
              equalRowHeights?: T;
              backgroundColor?: T;
              fullBleed?: T;
              cellDividers?: T;
              cellDividerColor?: T;
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              backgroundImage?: T;
              focalPointY?: T;
              centered?: T;
              focalPointX?: T;
              overlay?: T;
              overlayStrength?: T;
              alignment?: T;
              height?: T;
              content?:
                | T
                | {
                    heroHeadline?:
                      | T
                      | {
                          text?: T;
                          fontSize?: T;
                          id?: T;
                          blockName?: T;
                        };
                    heroSubheadline?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                          blockName?: T;
                        };
                    heroRichText?:
                      | T
                      | {
                          content?: T;
                          layout?: T;
                          id?: T;
                          blockName?: T;
                        };
                    heroRotatingHeadline?:
                      | T
                      | {
                          prefix?: T;
                          rotatingWords?:
                            | T
                            | {
                                word?: T;
                                id?: T;
                              };
                          suffix?: T;
                          intervalMs?: T;
                          fontSize?: T;
                          id?: T;
                          blockName?: T;
                        };
                    heroCta?:
                      | T
                      | {
                          links?:
                            | T
                            | {
                                label?: T;
                                url?: T;
                                variant?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    heroSpacer?:
                      | T
                      | {
                          height?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        logoMarquee?:
          | T
          | {
              logos?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    id?: T;
                  };
              logoSize?: T;
              speed?: T;
              pauseOnHover?: T;
              colorizeOnHover?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              variant?: T;
              width?: T;
              renderFloating?: T;
              floatingOffset?: T;
              margin?: T;
              backgroundColor?: T;
              fullBleed?: T;
              darken?: T;
              darkenStrength?: T;
              roundedCorners?: T;
              id?: T;
              blockName?: T;
            };
        rotatingHeadline?:
          | T
          | {
              prefix?: T;
              rotatingWords?:
                | T
                | {
                    word?: T;
                    id?: T;
                  };
              suffix?: T;
              alignment?: T;
              intervalMs?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              height?: T;
              id?: T;
              blockName?: T;
            };
        splitTextImage?:
          | T
          | {
              text?: T;
              buttons?:
                | T
                | {
                    caption?: T;
                    link?: T;
                    id?: T;
                  };
              mediaType?: T;
              image?: T;
              focalPointX?: T;
              focalPointY?: T;
              vimeoId?: T;
              videoPoster?: T;
              videoCtaCaption?: T;
              imagePosition?: T;
              imagePercentage?: T;
              imageSizingMode?: T;
              imageRatio?: T;
              imageVerticalMargin?: T;
              imageHorizontalMargin?: T;
              imageSize?: T;
              textContainerMargin?: T;
              backgroundColor?: T;
              fullBleed?: T;
              roundedCorners?: T;
              collapsedByDefault?: T;
              startNumberedListAtZero?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              testimonials?:
                | T
                | {
                    quote?: T;
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              vimeoId?: T;
              posterImage?: T;
              ctaCaption?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The name of your website, displayed in the header when no logo is set
   */
  siteTitle: string;
  /**
   * Color used for the site title in the header when no logo is set
   */
  titleColor?: string | null;
  /**
   * Site logo image. If set, this will be displayed in the header instead of the site title
   */
  logo?: (number | null) | Media;
  /**
   * Favicon for the site. Recommended size: 32x32 or 64x64 pixels. Supported formats: ICO, PNG, SVG
   */
  favicon?: (number | null) | Media;
  /**
   * Visual styling options for your website
   */
  styling?: {
    /**
     * Maximum width of the main content container
     */
    containerWidth?: ('narrower' | 'default' | 'wider') | null;
    /**
     * Horizontal alignment of the navigation menu in the header
     */
    headerMenuAlignment?: ('left' | 'center' | 'right') | null;
    /**
     * Height of the site header
     */
    headerHeight?: ('small' | 'medium' | 'large' | 'xl' | '2xl') | null;
    /**
     * Show a bottom border on the header
     */
    headerBorder?: boolean | null;
    /**
     * Width of the logo in the header. Height adjusts automatically to maintain aspect ratio.
     */
    logoSize?: ('small' | 'medium' | 'large' | 'xl') | null;
    /**
     * Vertical spacing between content blocks on a page
     */
    blockSpacing?: ('tight' | 'narrower' | 'default' | 'wider' | 'spacious') | null;
    /**
     * Google Font for body text (e.g., "Roboto", "Open Sans"). Leave empty for system default.
     */
    googleFontBody?: string | null;
    /**
     * Google Font for H1 headings (e.g., "Playfair Display", "Montserrat"). Leave empty to use body font.
     */
    googleFontH1?: string | null;
    /**
     * Google Font for H2-H6 headings (e.g., "Raleway", "Oswald"). Leave empty to use body font.
     */
    googleFontHeadings?: string | null;
  };
  /**
   * Footer configuration options
   */
  footer?: {
    /**
     * Links displayed in the bottom right of the footer
     */
    links?:
      | {
          /**
           * Display text for the link
           */
          text: string;
          /**
           * URL the link points to (can be internal like /about or external like https://example.com). Leave empty to render as a plain label.
           */
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Custom HTML content to inject into the <head> element
   */
  headContent?: {
    /**
     * HTML content inserted at the beginning of <head>. Use for meta tags, early scripts, or preload hints.
     */
    leading?: string | null;
    /**
     * HTML content inserted at the end of <head>. Use for analytics scripts, tracking pixels, or custom styles.
     */
    tailing?: string | null;
  };
  /**
   * A cookie consent banner displayed at the bottom of the screen. Users can accept or reject cookies.
   */
  cookieConsent?: {
    /**
     * Toggle the cookie consent banner on or off
     */
    enabled?: boolean | null;
    /**
     * The banner text (e.g. "We use cookies to improve your experience.")
     */
    message?: string | null;
    /**
     * Text for the accept button
     */
    acceptLabel?: string | null;
    /**
     * Link to the cookie policy page
     */
    policyUrl?: string | null;
    /**
     * Anchor text for the policy page link
     */
    policyLinkText?: string | null;
  };
  /**
   * A floating message pinned to the bottom-right of the screen. Leave content empty to hide it.
   */
  stickyMessage?: {
    /**
     * Message content. Only basic formatting (bold, italic, underline, strikethrough) and links are available.
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Whether users can dismiss the message. If unchecked, the message is always visible.
     */
    closeable?: boolean | null;
  };
  /**
   * Configure the free e-book download. Any button or link on the site whose URL is set to "#ebook" opens a popup with a small lead form (name + email). On submit the lead is captured in Mailchimp (client-side, no server) and the PDF downloads instantly in the browser.
   */
  ebook?: {
    /**
     * Master switch — when off, "#ebook" links do nothing special.
     */
    enabled?: boolean | null;
    /**
     * Mailchimp classic form action URL for the e-book leads audience, e.g. https://xxx.us21.list-manage.com/subscribe/post-json?u=...&id=... — same kind of URL as the Newsletter block. Leave empty to skip lead capture (the PDF still downloads).
     */
    mailchimpActionUrl?: string | null;
    /**
     * The PDF that is offered for download after the lead form is submitted.
     */
    pdf?: (number | null) | Media;
    /**
     * Optional. Used as a hint/label where a generic e-book trigger is rendered.
     */
    buttonCaption?: string | null;
  };
  /**
   * A floating flash message that pops into a corner of the screen. Use for time-bounded notices: announcements, promotions, transient updates.
   */
  toast?: {
    /**
     * Master switch — turn the toast on or off without losing its configuration.
     */
    enabled?: boolean | null;
    /**
     * Toast text. Keep it short — one line reads best. You can insert inline buttons via the toolbar.
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Background color of the toast.
     */
    backgroundColor?: string | null;
    /**
     * Where the toast appears on screen.
     */
    position?: ('bottomRight' | 'bottomLeft' | 'topRight' | 'topLeft') | null;
    /**
     * How long to wait after page load before the toast appears. Set to 0 to show immediately.
     */
    displayDelaySeconds?: number | null;
    /**
     * Show a close button so visitors can dismiss the toast.
     */
    dismissible?: boolean | null;
    /**
     * Automatically hide the toast after this many seconds. Set to 0 to keep it open until dismissed.
     */
    autoDismissSeconds?: number | null;
    /**
     * When checked, visitors who dismiss the toast will not see it again (stored in their browser).
     */
    rememberDismissal?: boolean | null;
    /**
     * A short identifier for this toast. Change it (e.g. "toast-2") to re-show the toast to visitors who already dismissed the previous one.
     */
    dismissalKey?: string | null;
    /**
     * Choose whether the toast is shown site-wide or only on selected pages.
     */
    pageVisibility?: ('all' | 'specific') | null;
    /**
     * Pick the pages where the toast should appear.
     */
    pages?: (number | Page)[] | null;
    /**
     * Optional. The toast will only appear from this date onward. Leave empty to start immediately.
     */
    startDate?: string | null;
    /**
     * Optional. The toast will stop appearing after this date. Leave empty to keep it active indefinitely.
     */
    endDate?: string | null;
  };
  /**
   * Configure a landing/entrance page that appears when visitors hit the root URL. It replaces the normal home page and hides the header/footer.
   */
  splashPage?: {
    /**
     * When enabled, visitors will see the splash page instead of the normal home page
     */
    enabled?: boolean | null;
    /**
     * Full-screen background image for the splash page. Use a high-resolution image for best results.
     */
    backgroundImage?: (number | null) | Media;
    /**
     * Apply a dark or light overlay on the background image to improve text readability
     */
    backgroundOverlay?: ('none' | 'darken' | 'lighten') | null;
    /**
     * Overlay strength in % (0 = transparent, 100 = fully opaque)
     */
    backgroundOverlayStrength?: number | null;
    /**
     * Centers all content horizontally and vertically in a full-screen (100vw x 100vh) wrapper
     */
    centered?: boolean | null;
    /**
     * Add and arrange content blocks for the splash page
     */
    content?:
      | (
          | {
              /**
               * Tally form ID (from the Tally embed URL, e.g. "81x1GP")
               */
              tallyFormId: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'contactForm';
            }
          | {
              /**
               * Add content cells to the grid
               */
              cells: {
                /**
                 * What this cell holds. A stat counter shows a large number that counts up from zero when it scrolls into view.
                 */
                elementType?: ('richText' | 'counter') | null;
                /**
                 * Cell content
                 */
                content?: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                } | null;
                /**
                 * Truncate this cell with a fade-out and a "Lees meer" button that expands the full content.
                 */
                collapsedByDefault?: boolean | null;
                /**
                 * How many lines to show before fading out.
                 */
                collapsedLines?: ('5' | '8' | '12' | '16' | '20') | null;
                /**
                 * The target number to count up to.
                 */
                counterValue?: number | null;
                /**
                 * Show the infinity symbol (∞) instead of a number. The counter still animates up, then cross-fades to ∞.
                 */
                counterInfinite?: boolean | null;
                /**
                 * Append a "+" after the number (e.g. "8+").
                 */
                counterShowPlus?: boolean | null;
                /**
                 * Caption shown beneath the number (e.g. "Jaren ervaring").
                 */
                counterLabel?: string | null;
                /**
                 * Color of the number (the label stays in the muted body color).
                 */
                counterColor?: string | null;
                id?: string | null;
              }[];
              /**
               * Number of columns on desktop
               */
              numberOfColumns?: ('2' | '3' | '4' | '5') | null;
              /**
               * Horizontal text alignment within cells
               */
              horizontalAlignment?: ('left' | 'center' | 'right') | null;
              /**
               * Vertical alignment of cells
               */
              verticalAlignment?: ('top' | 'center' | 'bottom') | null;
              /**
               * Show a small 01/02/… index and hairline rule above each cell — reads like a magazine spread. Best on 2–4 column left-aligned grids.
               */
              editorialNumbers?: boolean | null;
              /**
               * Wrap each cell in a translucent card with padding.
               */
              renderAsCards?: boolean | null;
              /**
               * Card background tone.
               */
              cardBackground?: ('lighten' | 'darken') | null;
              /**
               * Apply rounded corners to each card.
               */
              cardRoundedCorners?: boolean | null;
              /**
               * Stretch every cell in a row to match the tallest one. Most visible when cells render as cards.
               */
              equalRowHeights?: boolean | null;
              /**
               * Background color for the whole grid (adds padding around the cells).
               */
              backgroundColor?: string | null;
              /**
               * Background color stretches horizontally across the full page width (cells stay within the container).
               */
              fullBleed?: boolean | null;
              /**
               * Draw subtle hairline rules between cells, like the columns of a magazine spread.
               */
              cellDividers?: boolean | null;
              /**
               * Color of the dividing lines (rendered at low opacity).
               */
              cellDividerColor?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'contentGrid';
            }
          | {
              /**
               * Background image for the hero section
               */
              backgroundImage?: (number | null) | Media;
              /**
               * Vertical focal point in % (0 = top, 50 = center, 100 = bottom)
               */
              focalPointY?: number | null;
              /**
               * Center the background image horizontally. Uncheck to set a custom horizontal focal point.
               */
              centered?: boolean | null;
              /**
               * Horizontal focal point in % (0 = left, 50 = center, 100 = right)
               */
              focalPointX?: number | null;
              /**
               * Apply a dark or light overlay on the background image to improve text readability
               */
              overlay?: ('none' | 'darken' | 'lighten') | null;
              /**
               * Overlay strength in % (0 = transparent, 100 = fully opaque)
               */
              overlayStrength?: number | null;
              /**
               * Text alignment within the hero
               */
              alignment?: ('left' | 'center' | 'right') | null;
              /**
               * Height of the hero section
               */
              height?: ('small' | 'medium' | 'large' | 'xl' | 'xxl' | 'xxxl') | null;
              /**
               * Add and arrange content within the hero
               */
              content?:
                | (
                    | {
                        /**
                         * The main headline text. Select text to color individual words or phrases.
                         */
                        text: {
                          root: {
                            type: string;
                            children: {
                              type: any;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        };
                        /**
                         * Heading level — matches the WYSIWYG heading sizes.
                         */
                        fontSize: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'heroHeadline';
                      }
                    | {
                        /**
                         * Supporting text below the headline. Select text to color individual words or phrases.
                         */
                        text: {
                          root: {
                            type: string;
                            children: {
                              type: any;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        };
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'heroSubheadline';
                      }
                    | {
                        content: {
                          root: {
                            type: string;
                            children: {
                              type: any;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        };
                        /**
                         * Content width and alignment within the hero
                         */
                        layout?: ('full' | 'left' | 'right') | null;
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'heroRichText';
                      }
                    | {
                        /**
                         * Static text shown before the rotating words (e.g. "We help you")
                         */
                        prefix?: string | null;
                        /**
                         * Words that cycle one after the other (minimum 2)
                         */
                        rotatingWords: {
                          word: string;
                          id?: string | null;
                        }[];
                        /**
                         * Optional static text shown after the rotating words
                         */
                        suffix?: string | null;
                        /**
                         * How long each word stays on screen, in milliseconds
                         */
                        intervalMs?: number | null;
                        /**
                         * Heading level — matches the WYSIWYG heading sizes.
                         */
                        fontSize: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'heroRotatingHeadline';
                      }
                    | {
                        /**
                         * Call-to-action buttons (max 4)
                         */
                        links: {
                          label: string;
                          /**
                           * URL or path (e.g., /contact or https://example.com)
                           */
                          url: string;
                          variant?: ('solid' | 'outline' | 'ghost') | null;
                          id?: string | null;
                        }[];
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'heroCta';
                      }
                    | {
                        /**
                         * Height of the spacer within the hero
                         */
                        height: 'xs' | 'small' | 'medium' | 'large' | 'xl';
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'heroSpacer';
                      }
                  )[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'hero';
            }
          | {
              /**
               * Heading text, e.g. "Subscribe to our newsletter"
               */
              heading?: string | null;
              /**
               * Optional supporting text below the heading
               */
              description?: string | null;
              /**
               * Text for the submit button
               */
              buttonLabel?: string | null;
              /**
               * Placeholder text for the email input, e.g. "Your email address"
               */
              emailPlaceholder?: string | null;
              /**
               * Message shown after successful subscription
               */
              successMessage?: string | null;
              /**
               * Mailchimp form action URL (from embed code), e.g. "https://yourlist.us1.list-manage.com/subscribe/post?u=...&id=..."
               */
              mailchimpActionUrl: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'newsletterSignup';
            }
          | {
              content: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              /**
               * Body is regular prose. Hero is for panel/overlay taglines where the first paragraph should read as a display lede. Long-form applies magazine-style reading measure and a drop cap on the first paragraph.
               */
              variant?: ('body' | 'hero' | 'longForm') | null;
              width?: ('1/4' | '1/3' | 'half' | '2/3' | '3/4' | 'full') | null;
              /**
               * When enabled, the block will be rendered with absolute positioning inside a relative wrapper.
               */
              renderFloating?: boolean | null;
              /**
               * CSS value for vertical offset, e.g. "20px", "3em", "-10px"
               */
              floatingOffset?: string | null;
              /**
               * Vertical margin above and below the block
               */
              margin?: ('none' | 'small' | 'medium' | 'large') | null;
              /**
               * Background color for this block
               */
              backgroundColor?: string | null;
              /**
               * Color stretches horizontally across the full page width (content stays within container)
               */
              fullBleed?: boolean | null;
              /**
               * Lay a dark overlay over the background (like the hero) to lift text contrast — handy with the checkered pattern.
               */
              darken?: boolean | null;
              /**
               * Overlay strength in % (0 = transparent, 100 = fully opaque)
               */
              darkenStrength?: number | null;
              /**
               * Apply rounded corners to the block
               */
              roundedCorners?: boolean | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'richText';
            }
          | {
              /**
               * The height of the spacer
               */
              height: 'xxxs' | 'xxs' | 'xs' | 'small' | 'medium' | 'large' | 'xl' | 'xxl' | 'xxxl';
              id?: string | null;
              blockName?: string | null;
              blockType: 'spacer';
            }
          | {
              /**
               * Title and description text (use headings for the title)
               */
              text: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              /**
               * Call-to-action buttons
               */
              buttons?:
                | {
                    /**
                     * Button text
                     */
                    caption: string;
                    /**
                     * URL or path (e.g., /contact or https://example.com)
                     */
                    link: string;
                    id?: string | null;
                  }[]
                | null;
              /**
               * Choose between image or video for the visual element
               */
              mediaType?: ('image' | 'video') | null;
              /**
               * The image to display
               */
              image?: (number | null) | Media;
              /**
               * Horizontal focal point in % (0 = left, 50 = center, 100 = right)
               */
              focalPointX?: number | null;
              /**
               * Vertical focal point in % (0 = top, 50 = center, 100 = bottom)
               */
              focalPointY?: number | null;
              /**
               * Vimeo video ID (e.g., "123456789" from vimeo.com/123456789)
               */
              vimeoId?: string | null;
              /**
               * Poster image shown before the video plays
               */
              videoPoster?: (number | null) | Media;
              /**
               * Call-to-action text displayed over the video poster
               */
              videoCtaCaption?: string | null;
              /**
               * Position of the media relative to the text
               */
              imagePosition?: ('left' | 'right') | null;
              /**
               * Width percentage of the media section (20-80%)
               */
              imagePercentage?: number | null;
              /**
               * How to size the image: fixed aspect ratio or natural dimensions
               */
              imageSizingMode?: ('ratio' | 'natural') | null;
              /**
               * Aspect ratio of the image (width/height)
               */
              imageRatio?:
                | ('2/3' | '3/4' | '4/5' | '5/6' | '9/10' | '1/1' | '10/9' | '6/5' | '5/4' | '4/3' | '3/2')
                | null;
              /**
               * Vertical margin above and below the image
               */
              imageVerticalMargin?: ('none' | 'small' | 'medium' | 'large') | null;
              /**
               * Horizontal margin on left and right of the image
               */
              imageHorizontalMargin?: ('none' | 'small' | 'medium' | 'large') | null;
              /**
               * Maximum size of the image (maintains natural aspect ratio)
               */
              imageSize?:
                | (
                    | 'tiny-icon'
                    | 'small-icon'
                    | 'icon'
                    | 'large-icon'
                    | 'tiny'
                    | 'small'
                    | 'medium'
                    | 'large'
                    | 'xlarge'
                    | 'huge'
                  )
                | null;
              /**
               * Margin around the text container (centered within text section)
               */
              textContainerMargin?: ('none' | 'small' | 'medium' | 'large') | null;
              /**
               * Background color for this block
               */
              backgroundColor?: string | null;
              /**
               * Color stretches horizontally across the full page width (content stays within container)
               */
              fullBleed?: boolean | null;
              /**
               * Apply rounded corners to the entire block
               */
              roundedCorners?: boolean | null;
              /**
               * Text is collapsed to the height of the media with a fade effect. A "Lees meer" button expands it.
               */
              collapsedByDefault?: boolean | null;
              /**
               * If checked, numbered lists in this block start at 0 instead of 1
               */
              startNumberedListAtZero?: boolean | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'splitTextImage';
            }
          | {
              /**
               * Enter table data in CSV format. Each line is a row, columns separated by commas.
               */
              csvData: string;
              /**
               * Show borders between cells
               */
              showBorders?: boolean | null;
              /**
               * First row are column titles (styled differently)
               */
              firstRowAreTitles?: boolean | null;
              /**
               * Last row cells are clickable buttons
               */
              lastRowAreButtons?: boolean | null;
              /**
               * Button links in CSV format (one link per column, e.g., "/page1,/page2,/page3")
               */
              buttonLinksCsv?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'table';
            }
          | {
              /**
               * Add testimonials to display in the carousel
               */
              testimonials: {
                /**
                 * The testimonial quote text
                 */
                quote: string;
                /**
                 * Name of the person giving the testimonial (e.g. "John Doe (Company)")
                 */
                name: string;
                id?: string | null;
              }[];
              id?: string | null;
              blockName?: string | null;
              blockType: 'testimonials';
            }
          | {
              /**
               * Vimeo video ID (e.g., "123456789" from vimeo.com/123456789)
               */
              vimeoId: string;
              /**
               * Poster image shown before the video plays
               */
              posterImage: number | Media;
              /**
               * Call-to-action button text that appears over the poster image
               */
              ctaCaption?: string | null;
              /**
               * Width of the video player
               */
              width?: ('half' | '2/3' | '3/4' | 'full') | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'video';
            }
        )[]
      | null;
  };
  /**
   * Customize your brand colors. These override the default theme colors across the entire site. Use the "Name" fields to give each color a meaningful label (e.g. "Brand Red").
   */
  themeColors?: {
    theme1Label?: string | null;
    theme2Label?: string | null;
    theme3Label?: string | null;
    theme4Label?: string | null;
    theme5Label?: string | null;
    theme6Label?: string | null;
    theme7Label?: string | null;
    theme8Label?: string | null;
    /**
     * Default: #ffffff
     */
    mainBg?: string | null;
    /**
     * Default: #373031
     */
    font?: string | null;
    /**
     * Default: #8B5A4A
     */
    fontAccent?: string | null;
    /**
     * Default: #5E6E83
     */
    headings?: string | null;
    /**
     * Default: #373031
     */
    buttonFont?: string | null;
    /**
     * Default: transparent
     */
    buttonBg?: string | null;
    /**
     * Default: #ffffff
     */
    buttonFontHover?: string | null;
    /**
     * Default: #EA8928
     */
    buttonBgHover?: string | null;
    /**
     * Default: #EA8928
     */
    tableBorders?: string | null;
    /**
     * Default: #373031
     */
    bulletPoints?: string | null;
    /**
     * Default: #B6C9BB
     */
    stickyMessageTxt?: string | null;
    /**
     * Default: #5E6E83
     */
    stickyMessageBg?: string | null;
    /**
     * Default: #5E6E83
     */
    theme1?: string | null;
    /**
     * Default: #5E6E83
     */
    theme2?: string | null;
    /**
     * Default: #B6C9BB
     */
    theme3?: string | null;
    /**
     * Default: #BFEDC1
     */
    theme4?: string | null;
    /**
     * Default: #EA8928
     */
    theme5?: string | null;
    /**
     * Default: #656565
     */
    theme6?: string | null;
    /**
     * Default: #2C3E50
     */
    theme7?: string | null;
    /**
     * Default: #E74C3C
     */
    theme8?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  titleColor?: T;
  logo?: T;
  favicon?: T;
  styling?:
    | T
    | {
        containerWidth?: T;
        headerMenuAlignment?: T;
        headerHeight?: T;
        headerBorder?: T;
        logoSize?: T;
        blockSpacing?: T;
        googleFontBody?: T;
        googleFontH1?: T;
        googleFontHeadings?: T;
      };
  footer?:
    | T
    | {
        links?:
          | T
          | {
              text?: T;
              url?: T;
              id?: T;
            };
      };
  headContent?:
    | T
    | {
        leading?: T;
        tailing?: T;
      };
  cookieConsent?:
    | T
    | {
        enabled?: T;
        message?: T;
        acceptLabel?: T;
        policyUrl?: T;
        policyLinkText?: T;
      };
  stickyMessage?:
    | T
    | {
        content?: T;
        closeable?: T;
      };
  ebook?:
    | T
    | {
        enabled?: T;
        mailchimpActionUrl?: T;
        pdf?: T;
        buttonCaption?: T;
      };
  toast?:
    | T
    | {
        enabled?: T;
        content?: T;
        backgroundColor?: T;
        position?: T;
        displayDelaySeconds?: T;
        dismissible?: T;
        autoDismissSeconds?: T;
        rememberDismissal?: T;
        dismissalKey?: T;
        pageVisibility?: T;
        pages?: T;
        startDate?: T;
        endDate?: T;
      };
  splashPage?:
    | T
    | {
        enabled?: T;
        backgroundImage?: T;
        backgroundOverlay?: T;
        backgroundOverlayStrength?: T;
        centered?: T;
        content?:
          | T
          | {
              contactForm?:
                | T
                | {
                    tallyFormId?: T;
                    id?: T;
                    blockName?: T;
                  };
              contentGrid?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          elementType?: T;
                          content?: T;
                          collapsedByDefault?: T;
                          collapsedLines?: T;
                          counterValue?: T;
                          counterInfinite?: T;
                          counterShowPlus?: T;
                          counterLabel?: T;
                          counterColor?: T;
                          id?: T;
                        };
                    numberOfColumns?: T;
                    horizontalAlignment?: T;
                    verticalAlignment?: T;
                    editorialNumbers?: T;
                    renderAsCards?: T;
                    cardBackground?: T;
                    cardRoundedCorners?: T;
                    equalRowHeights?: T;
                    backgroundColor?: T;
                    fullBleed?: T;
                    cellDividers?: T;
                    cellDividerColor?: T;
                    id?: T;
                    blockName?: T;
                  };
              hero?:
                | T
                | {
                    backgroundImage?: T;
                    focalPointY?: T;
                    centered?: T;
                    focalPointX?: T;
                    overlay?: T;
                    overlayStrength?: T;
                    alignment?: T;
                    height?: T;
                    content?:
                      | T
                      | {
                          heroHeadline?:
                            | T
                            | {
                                text?: T;
                                fontSize?: T;
                                id?: T;
                                blockName?: T;
                              };
                          heroSubheadline?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                                blockName?: T;
                              };
                          heroRichText?:
                            | T
                            | {
                                content?: T;
                                layout?: T;
                                id?: T;
                                blockName?: T;
                              };
                          heroRotatingHeadline?:
                            | T
                            | {
                                prefix?: T;
                                rotatingWords?:
                                  | T
                                  | {
                                      word?: T;
                                      id?: T;
                                    };
                                suffix?: T;
                                intervalMs?: T;
                                fontSize?: T;
                                id?: T;
                                blockName?: T;
                              };
                          heroCta?:
                            | T
                            | {
                                links?:
                                  | T
                                  | {
                                      label?: T;
                                      url?: T;
                                      variant?: T;
                                      id?: T;
                                    };
                                id?: T;
                                blockName?: T;
                              };
                          heroSpacer?:
                            | T
                            | {
                                height?: T;
                                id?: T;
                                blockName?: T;
                              };
                        };
                    id?: T;
                    blockName?: T;
                  };
              newsletterSignup?:
                | T
                | {
                    heading?: T;
                    description?: T;
                    buttonLabel?: T;
                    emailPlaceholder?: T;
                    successMessage?: T;
                    mailchimpActionUrl?: T;
                    id?: T;
                    blockName?: T;
                  };
              richText?:
                | T
                | {
                    content?: T;
                    variant?: T;
                    width?: T;
                    renderFloating?: T;
                    floatingOffset?: T;
                    margin?: T;
                    backgroundColor?: T;
                    fullBleed?: T;
                    darken?: T;
                    darkenStrength?: T;
                    roundedCorners?: T;
                    id?: T;
                    blockName?: T;
                  };
              spacer?:
                | T
                | {
                    height?: T;
                    id?: T;
                    blockName?: T;
                  };
              splitTextImage?:
                | T
                | {
                    text?: T;
                    buttons?:
                      | T
                      | {
                          caption?: T;
                          link?: T;
                          id?: T;
                        };
                    mediaType?: T;
                    image?: T;
                    focalPointX?: T;
                    focalPointY?: T;
                    vimeoId?: T;
                    videoPoster?: T;
                    videoCtaCaption?: T;
                    imagePosition?: T;
                    imagePercentage?: T;
                    imageSizingMode?: T;
                    imageRatio?: T;
                    imageVerticalMargin?: T;
                    imageHorizontalMargin?: T;
                    imageSize?: T;
                    textContainerMargin?: T;
                    backgroundColor?: T;
                    fullBleed?: T;
                    roundedCorners?: T;
                    collapsedByDefault?: T;
                    startNumberedListAtZero?: T;
                    id?: T;
                    blockName?: T;
                  };
              table?:
                | T
                | {
                    csvData?: T;
                    showBorders?: T;
                    firstRowAreTitles?: T;
                    lastRowAreButtons?: T;
                    buttonLinksCsv?: T;
                    id?: T;
                    blockName?: T;
                  };
              testimonials?:
                | T
                | {
                    testimonials?:
                      | T
                      | {
                          quote?: T;
                          name?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              video?:
                | T
                | {
                    vimeoId?: T;
                    posterImage?: T;
                    ctaCaption?: T;
                    width?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  themeColors?:
    | T
    | {
        theme1Label?: T;
        theme2Label?: T;
        theme3Label?: T;
        theme4Label?: T;
        theme5Label?: T;
        theme6Label?: T;
        theme7Label?: T;
        theme8Label?: T;
        mainBg?: T;
        font?: T;
        fontAccent?: T;
        headings?: T;
        buttonFont?: T;
        buttonBg?: T;
        buttonFontHover?: T;
        buttonBgHover?: T;
        tableBorders?: T;
        bulletPoints?: T;
        stickyMessageTxt?: T;
        stickyMessageBg?: T;
        theme1?: T;
        theme2?: T;
        theme3?: T;
        theme4?: T;
        theme5?: T;
        theme6?: T;
        theme7?: T;
        theme8?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}