/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL slug for the page (e.g., "about-us")
   */
  slug: string;
  /**
   * Show this page in the main navigation menu
   */
  showInMenu?: boolean | null;
  /**
   * Order in the menu (lower numbers appear first)
   */
  menuOrder?: number | null;
  /**
   * Show this page as a call-to-action in the header toolbar (above main menu)
   */
  showInToolbar?: boolean | null;
  /**
   * Custom label for toolbar (uses page title if blank)
   */
  toolbarLabel?: string | null;
  /**
   * Order in the toolbar (lower numbers appear first)
   */
  toolbarOrder?: number | null;
  /**
   * If set, only these pages will appear in the main menu when viewing this page. Leave empty to show the full menu.
   */
  menuFilter?: (number | Page)[] | null;
  /**
   * Add and arrange content blocks for this page
   */
  content?:
    | (
        | {
            /**
             * Tally form ID (from the Tally embed URL, e.g. "81x1GP")
             */
            tallyFormId: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            /**
             * Add content cells to the grid
             */
            cells: {
              /**
               * Cell content
               */
              content: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            /**
             * Number of columns on desktop
             */
            numberOfColumns?: ('2' | '3' | '4' | '5') | null;
            /**
             * Horizontal text alignment within cells
             */
            horizontalAlignment?: ('left' | 'center' | 'right') | null;
            /**
             * Vertical alignment of cells
             */
            verticalAlignment?: ('top' | 'center' | 'bottom') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentGrid';
          }
        | {
            /**
             * The main headline text
             */
            headline?: string | null;
            /**
             * Supporting text below the headline
             */
            subheadline?: string | null;
            /**
             * Background image for the hero section
             */
            backgroundImage?: (number | null) | Media;
            /**
             * Vertical focal point in % (0 = top, 50 = center, 100 = bottom)
             */
            focalPointY?: number | null;
            /**
             * Text alignment within the hero
             */
            alignment?: ('left' | 'center' | 'right') | null;
            /**
             * Height of the hero section
             */
            height?: ('small' | 'medium' | 'large' | 'xl' | 'xxl') | null;
            /**
             * Call-to-action buttons (max 2)
             */
            links?:
              | {
                  label: string;
                  /**
                   * URL or path (e.g., /contact or https://example.com)
                   */
                  url: string;
                  variant?: ('solid' | 'outline' | 'ghost') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Add logo images to scroll in the marquee (minimum 3)
             */
            logos: {
              /**
               * Logo image (transparent PNG or SVG recommended)
               */
              image: number | Media;
              /**
               * Alt text for the logo (overrides media alt text)
               */
              alt?: string | null;
              id?: string | null;
            }[];
            /**
             * Uniform height of the logos
             */
            logoSize?: ('small' | 'medium' | 'large') | null;
            /**
             * Scrolling speed of the marquee
             */
            speed?: ('slow' | 'medium' | 'fast') | null;
            /**
             * Pause the marquee when the user hovers over it
             */
            pauseOnHover?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoMarquee';
          }
        | {
            /**
             * Heading text, e.g. "Subscribe to our newsletter"
             */
            heading?: string | null;
            /**
             * Optional supporting text below the heading
             */
            description?: string | null;
            /**
             * Text for the submit button
             */
            buttonLabel?: string | null;
            /**
             * Placeholder text for the email input, e.g. "Your email address"
             */
            emailPlaceholder?: string | null;
            /**
             * Message shown after successful subscription
             */
            successMessage?: string | null;
            /**
             * Mailchimp form action URL (from embed code), e.g. "https://yourlist.us1.list-manage.com/subscribe/post?u=...&id=..."
             */
            mailchimpActionUrl: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletterSignup';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            width?: ('1/4' | '1/3' | 'half' | '2/3' | '3/4' | 'full') | null;
            /**
             * When enabled, the block will be rendered with absolute positioning inside a relative wrapper.
             */
            renderFloating?: boolean | null;
            /**
             * CSS value for vertical offset, e.g. "20px", "3em", "-10px"
             */
            floatingOffset?: string | null;
            /**
             * Vertical margin above and below the block
             */
            margin?: ('none' | 'small' | 'medium' | 'large') | null;
            /**
             * Background color for this block
             */
            backgroundColor?: string | null;
            /**
             * Apply rounded corners to the block
             */
            roundedCorners?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * The height of the spacer
             */
            height: 'xxxs' | 'xxs' | 'xs' | 'small' | 'medium' | 'large' | 'xl' | 'xxl' | 'xxxl';
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer';
          }
        | {
            /**
             * Title and description text (use headings for the title)
             */
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Call-to-action buttons
             */
            buttons?:
              | {
                  /**
                   * Button text
                   */
                  caption: string;
                  /**
                   * URL or path (e.g., /contact or https://example.com)
                   */
                  link: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Choose between image or video for the visual element
             */
            mediaType?: ('image' | 'video') | null;
            /**
             * The image to display
             */
            image?: (number | null) | Media;
            /**
             * Horizontal focal point in % (0 = left, 50 = center, 100 = right)
             */
            focalPointX?: number | null;
            /**
             * Vertical focal point in % (0 = top, 50 = center, 100 = bottom)
             */
            focalPointY?: number | null;
            /**
             * Vimeo video ID (e.g., "123456789" from vimeo.com/123456789)
             */
            vimeoId?: string | null;
            /**
             * Poster image shown before the video plays
             */
            videoPoster?: (number | null) | Media;
            /**
             * Call-to-action text displayed over the video poster
             */
            videoCtaCaption?: string | null;
            /**
             * Position of the media relative to the text
             */
            imagePosition?: ('left' | 'right') | null;
            /**
             * Width percentage of the media section (20-80%)
             */
            imagePercentage?: number | null;
            /**
             * How to size the image: fixed aspect ratio or natural dimensions
             */
            imageSizingMode?: ('ratio' | 'natural') | null;
            /**
             * Aspect ratio of the image (width/height)
             */
            imageRatio?:
              | ('2/3' | '3/4' | '4/5' | '5/6' | '9/10' | '1/1' | '10/9' | '6/5' | '5/4' | '4/3' | '3/2')
              | null;
            /**
             * Vertical margin above and below the image
             */
            imageVerticalMargin?: ('none' | 'small' | 'medium' | 'large') | null;
            /**
             * Horizontal margin on left and right of the image
             */
            imageHorizontalMargin?: ('none' | 'small' | 'medium' | 'large') | null;
            /**
             * Maximum size of the image (maintains natural aspect ratio)
             */
            imageSize?:
              | (
                  | 'tiny-icon'
                  | 'small-icon'
                  | 'icon'
                  | 'large-icon'
                  | 'tiny'
                  | 'small'
                  | 'medium'
                  | 'large'
                  | 'xlarge'
                  | 'huge'
                )
              | null;
            /**
             * Margin around the text container (centered within text section)
             */
            textContainerMargin?: ('none' | 'small' | 'medium' | 'large') | null;
            /**
             * Background color for this block
             */
            backgroundColor?: string | null;
            /**
             * Color stretches horizontally across the full page width (content stays within container)
             */
            fullBleed?: boolean | null;
            /**
             * Apply rounded corners to the entire block
             */
            roundedCorners?: boolean | null;
            /**
             * Text is collapsed to the height of the media with a fade effect. A "Lees meer" button expands it.
             */
            collapsedByDefault?: boolean | null;
            /**
             * If checked, numbered lists in this block start at 0 instead of 1
             */
            startNumberedListAtZero?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitTextImage';
          }
        | {
            /**
             * Enter table data in CSV format. Each line is a row, columns separated by commas.
             */
            csvData: string;
            /**
             * Show borders between cells
             */
            showBorders?: boolean | null;
            /**
             * First row are column titles (styled differently)
             */
            firstRowAreTitles?: boolean | null;
            /**
             * Last row cells are clickable buttons
             */
            lastRowAreButtons?: boolean | null;
            /**
             * Button links in CSV format (one link per column, e.g., "/page1,/page2,/page3")
             */
            buttonLinksCsv?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'table';
          }
        | {
            /**
             * Add testimonials to display in the carousel
             */
            testimonials: {
              /**
               * The testimonial quote text
               */
              quote: string;
              /**
               * Name of the person giving the testimonial (e.g. "John Doe (Company)")
               */
              name: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            /**
             * Vimeo video ID (e.g., "123456789" from vimeo.com/123456789)
             */
            vimeoId: string;
            /**
             * Poster image shown before the video plays
             */
            posterImage: number | Media;
            /**
             * Call-to-action button text that appears over the poster image
             */
            ctaCaption?: string | null;
            /**
             * Width of the video player
             */
            width?: ('half' | '2/3' | '3/4' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
      )[]
    | null;
  /**
   * Search engine optimization settings
   */
  seo?: {
    /**
     * Meta description for search engines (recommended: 150-160 characters)
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility
   */
  alt?: string | null;
  /**
   * Optional caption to display below the image
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * User role for access control
   */
  role: 'admin' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  showInMenu?: T;
  menuOrder?: T;
  showInToolbar?: T;
  toolbarLabel?: T;
  toolbarOrder?: T;
  menuFilter?: T;
  content?:
    | T
    | {
        contactForm?:
          | T
          | {
              tallyFormId?: T;
              id?: T;
              blockName?: T;
            };
        contentGrid?:
          | T
          | {
              cells?:
                | T
                | {
                    content?: T;
                    id?: T;
                  };
              numberOfColumns?: T;
              horizontalAlignment?: T;
              verticalAlignment?: T;
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              backgroundImage?: T;
              focalPointY?: T;
              alignment?: T;
              height?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoMarquee?:
          | T
          | {
              logos?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    id?: T;
                  };
              logoSize?: T;
              speed?: T;
              pauseOnHover?: T;
              id?: T;
              blockName?: T;
            };
        newsletterSignup?:
          | T
          | {
              heading?: T;
              description?: T;
              buttonLabel?: T;
              emailPlaceholder?: T;
              successMessage?: T;
              mailchimpActionUrl?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              width?: T;
              renderFloating?: T;
              floatingOffset?: T;
              margin?: T;
              backgroundColor?: T;
              roundedCorners?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              height?: T;
              id?: T;
              blockName?: T;
            };
        splitTextImage?:
          | T
          | {
              text?: T;
              buttons?:
                | T
                | {
                    caption?: T;
                    link?: T;
                    id?: T;
                  };
              mediaType?: T;
              image?: T;
              focalPointX?: T;
              focalPointY?: T;
              vimeoId?: T;
              videoPoster?: T;
              videoCtaCaption?: T;
              imagePosition?: T;
              imagePercentage?: T;
              imageSizingMode?: T;
              imageRatio?: T;
              imageVerticalMargin?: T;
              imageHorizontalMargin?: T;
              imageSize?: T;
              textContainerMargin?: T;
              backgroundColor?: T;
              fullBleed?: T;
              roundedCorners?: T;
              collapsedByDefault?: T;
              startNumberedListAtZero?: T;
              id?: T;
              blockName?: T;
            };
        table?:
          | T
          | {
              csvData?: T;
              showBorders?: T;
              firstRowAreTitles?: T;
              lastRowAreButtons?: T;
              buttonLinksCsv?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              testimonials?:
                | T
                | {
                    quote?: T;
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              vimeoId?: T;
              posterImage?: T;
              ctaCaption?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The name of your website, displayed in the header when no logo is set
   */
  siteTitle: string;
  /**
   * Site logo image. If set, this will be displayed in the header instead of the site title
   */
  logo?: (number | null) | Media;
  /**
   * Favicon for the site. Recommended size: 32x32 or 64x64 pixels. Supported formats: ICO, PNG, SVG
   */
  favicon?: (number | null) | Media;
  /**
   * Visual styling options for your website
   */
  styling?: {
    /**
     * Maximum width of the main content container
     */
    containerWidth?: ('narrower' | 'default' | 'wider') | null;
    /**
     * Horizontal alignment of the navigation menu in the header
     */
    headerMenuAlignment?: ('left' | 'center' | 'right') | null;
    /**
     * Height of the site header
     */
    headerHeight?: ('small' | 'medium' | 'large' | 'xl' | '2xl') | null;
    /**
     * Show a bottom border on the header
     */
    headerBorder?: boolean | null;
    /**
     * Width of the logo in the header. Height adjusts automatically to maintain aspect ratio.
     */
    logoSize?: ('small' | 'medium' | 'large' | 'xl') | null;
    /**
     * Background color for the header
     */
    headerBackgroundColor?: string | null;
    /**
     * Background color for the website
     */
    backgroundColor?: string | null;
    /**
     * Google Font name to use for all text (e.g., "Roboto", "Open Sans", "Lato"). Leave empty for system default.
     */
    googleFont?: string | null;
  };
  /**
   * Footer configuration options
   */
  footer?: {
    /**
     * Links displayed in the bottom right of the footer
     */
    links?:
      | {
          /**
           * Display text for the link
           */
          text: string;
          /**
           * URL the link points to (can be internal like /about or external like https://example.com)
           */
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Custom HTML content to inject into the <head> element
   */
  headContent?: {
    /**
     * HTML content inserted at the beginning of <head>. Use for meta tags, early scripts, or preload hints.
     */
    leading?: string | null;
    /**
     * HTML content inserted at the end of <head>. Use for analytics scripts, tracking pixels, or custom styles.
     */
    tailing?: string | null;
  };
  /**
   * A cookie consent banner displayed at the bottom of the screen. Users can accept or reject cookies.
   */
  cookieConsent?: {
    /**
     * Toggle the cookie consent banner on or off
     */
    enabled?: boolean | null;
    /**
     * The banner text (e.g. "We use cookies to improve your experience.")
     */
    message?: string | null;
    /**
     * Text for the accept button
     */
    acceptLabel?: string | null;
    /**
     * Link to the cookie policy page
     */
    policyUrl?: string | null;
    /**
     * Anchor text for the policy page link
     */
    policyLinkText?: string | null;
  };
  /**
   * A floating message pinned to the bottom-right of the screen. Leave content empty to hide it.
   */
  stickyMessage?: {
    /**
     * Message content. Only basic formatting (bold, italic, underline, strikethrough) and links are available.
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Whether users can dismiss the message. If unchecked, the message is always visible.
     */
    closeable?: boolean | null;
  };
  /**
   * Configure a landing/entrance page that appears when visitors hit the root URL. It replaces the normal home page and hides the header/footer.
   */
  splashPage?: {
    /**
     * When enabled, visitors will see the splash page instead of the normal home page
     */
    enabled?: boolean | null;
    /**
     * Centers all content horizontally and vertically in a full-screen (100vw x 100vh) wrapper
     */
    centered?: boolean | null;
    /**
     * Add and arrange content blocks for the splash page
     */
    content?:
      | (
          | {
              /**
               * Tally form ID (from the Tally embed URL, e.g. "81x1GP")
               */
              tallyFormId: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'contactForm';
            }
          | {
              /**
               * Add content cells to the grid
               */
              cells: {
                /**
                 * Cell content
                 */
                content: {
                  root: {
                    type: string;
                    children: {
                      type: any;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                };
                id?: string | null;
              }[];
              /**
               * Number of columns on desktop
               */
              numberOfColumns?: ('2' | '3' | '4' | '5') | null;
              /**
               * Horizontal text alignment within cells
               */
              horizontalAlignment?: ('left' | 'center' | 'right') | null;
              /**
               * Vertical alignment of cells
               */
              verticalAlignment?: ('top' | 'center' | 'bottom') | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'contentGrid';
            }
          | {
              /**
               * The main headline text
               */
              headline?: string | null;
              /**
               * Supporting text below the headline
               */
              subheadline?: string | null;
              /**
               * Background image for the hero section
               */
              backgroundImage?: (number | null) | Media;
              /**
               * Vertical focal point in % (0 = top, 50 = center, 100 = bottom)
               */
              focalPointY?: number | null;
              /**
               * Text alignment within the hero
               */
              alignment?: ('left' | 'center' | 'right') | null;
              /**
               * Height of the hero section
               */
              height?: ('small' | 'medium' | 'large' | 'xl' | 'xxl') | null;
              /**
               * Call-to-action buttons (max 2)
               */
              links?:
                | {
                    label: string;
                    /**
                     * URL or path (e.g., /contact or https://example.com)
                     */
                    url: string;
                    variant?: ('solid' | 'outline' | 'ghost') | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'hero';
            }
          | {
              /**
               * Heading text, e.g. "Subscribe to our newsletter"
               */
              heading?: string | null;
              /**
               * Optional supporting text below the heading
               */
              description?: string | null;
              /**
               * Text for the submit button
               */
              buttonLabel?: string | null;
              /**
               * Placeholder text for the email input, e.g. "Your email address"
               */
              emailPlaceholder?: string | null;
              /**
               * Message shown after successful subscription
               */
              successMessage?: string | null;
              /**
               * Mailchimp form action URL (from embed code), e.g. "https://yourlist.us1.list-manage.com/subscribe/post?u=...&id=..."
               */
              mailchimpActionUrl: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'newsletterSignup';
            }
          | {
              content: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              width?: ('1/4' | '1/3' | 'half' | '2/3' | '3/4' | 'full') | null;
              /**
               * When enabled, the block will be rendered with absolute positioning inside a relative wrapper.
               */
              renderFloating?: boolean | null;
              /**
               * CSS value for vertical offset, e.g. "20px", "3em", "-10px"
               */
              floatingOffset?: string | null;
              /**
               * Vertical margin above and below the block
               */
              margin?: ('none' | 'small' | 'medium' | 'large') | null;
              /**
               * Background color for this block
               */
              backgroundColor?: string | null;
              /**
               * Apply rounded corners to the block
               */
              roundedCorners?: boolean | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'richText';
            }
          | {
              /**
               * The height of the spacer
               */
              height: 'xxxs' | 'xxs' | 'xs' | 'small' | 'medium' | 'large' | 'xl' | 'xxl' | 'xxxl';
              id?: string | null;
              blockName?: string | null;
              blockType: 'spacer';
            }
          | {
              /**
               * Title and description text (use headings for the title)
               */
              text: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              /**
               * Call-to-action buttons
               */
              buttons?:
                | {
                    /**
                     * Button text
                     */
                    caption: string;
                    /**
                     * URL or path (e.g., /contact or https://example.com)
                     */
                    link: string;
                    id?: string | null;
                  }[]
                | null;
              /**
               * Choose between image or video for the visual element
               */
              mediaType?: ('image' | 'video') | null;
              /**
               * The image to display
               */
              image?: (number | null) | Media;
              /**
               * Horizontal focal point in % (0 = left, 50 = center, 100 = right)
               */
              focalPointX?: number | null;
              /**
               * Vertical focal point in % (0 = top, 50 = center, 100 = bottom)
               */
              focalPointY?: number | null;
              /**
               * Vimeo video ID (e.g., "123456789" from vimeo.com/123456789)
               */
              vimeoId?: string | null;
              /**
               * Poster image shown before the video plays
               */
              videoPoster?: (number | null) | Media;
              /**
               * Call-to-action text displayed over the video poster
               */
              videoCtaCaption?: string | null;
              /**
               * Position of the media relative to the text
               */
              imagePosition?: ('left' | 'right') | null;
              /**
               * Width percentage of the media section (20-80%)
               */
              imagePercentage?: number | null;
              /**
               * How to size the image: fixed aspect ratio or natural dimensions
               */
              imageSizingMode?: ('ratio' | 'natural') | null;
              /**
               * Aspect ratio of the image (width/height)
               */
              imageRatio?:
                | ('2/3' | '3/4' | '4/5' | '5/6' | '9/10' | '1/1' | '10/9' | '6/5' | '5/4' | '4/3' | '3/2')
                | null;
              /**
               * Vertical margin above and below the image
               */
              imageVerticalMargin?: ('none' | 'small' | 'medium' | 'large') | null;
              /**
               * Horizontal margin on left and right of the image
               */
              imageHorizontalMargin?: ('none' | 'small' | 'medium' | 'large') | null;
              /**
               * Maximum size of the image (maintains natural aspect ratio)
               */
              imageSize?:
                | (
                    | 'tiny-icon'
                    | 'small-icon'
                    | 'icon'
                    | 'large-icon'
                    | 'tiny'
                    | 'small'
                    | 'medium'
                    | 'large'
                    | 'xlarge'
                    | 'huge'
                  )
                | null;
              /**
               * Margin around the text container (centered within text section)
               */
              textContainerMargin?: ('none' | 'small' | 'medium' | 'large') | null;
              /**
               * Background color for this block
               */
              backgroundColor?: string | null;
              /**
               * Color stretches horizontally across the full page width (content stays within container)
               */
              fullBleed?: boolean | null;
              /**
               * Apply rounded corners to the entire block
               */
              roundedCorners?: boolean | null;
              /**
               * Text is collapsed to the height of the media with a fade effect. A "Lees meer" button expands it.
               */
              collapsedByDefault?: boolean | null;
              /**
               * If checked, numbered lists in this block start at 0 instead of 1
               */
              startNumberedListAtZero?: boolean | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'splitTextImage';
            }
          | {
              /**
               * Enter table data in CSV format. Each line is a row, columns separated by commas.
               */
              csvData: string;
              /**
               * Show borders between cells
               */
              showBorders?: boolean | null;
              /**
               * First row are column titles (styled differently)
               */
              firstRowAreTitles?: boolean | null;
              /**
               * Last row cells are clickable buttons
               */
              lastRowAreButtons?: boolean | null;
              /**
               * Button links in CSV format (one link per column, e.g., "/page1,/page2,/page3")
               */
              buttonLinksCsv?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'table';
            }
          | {
              /**
               * Add testimonials to display in the carousel
               */
              testimonials: {
                /**
                 * The testimonial quote text
                 */
                quote: string;
                /**
                 * Name of the person giving the testimonial (e.g. "John Doe (Company)")
                 */
                name: string;
                id?: string | null;
              }[];
              id?: string | null;
              blockName?: string | null;
              blockType: 'testimonials';
            }
          | {
              /**
               * Vimeo video ID (e.g., "123456789" from vimeo.com/123456789)
               */
              vimeoId: string;
              /**
               * Poster image shown before the video plays
               */
              posterImage: number | Media;
              /**
               * Call-to-action button text that appears over the poster image
               */
              ctaCaption?: string | null;
              /**
               * Width of the video player
               */
              width?: ('half' | '2/3' | '3/4' | 'full') | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'video';
            }
        )[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  logo?: T;
  favicon?: T;
  styling?:
    | T
    | {
        containerWidth?: T;
        headerMenuAlignment?: T;
        headerHeight?: T;
        headerBorder?: T;
        logoSize?: T;
        headerBackgroundColor?: T;
        backgroundColor?: T;
        googleFont?: T;
      };
  footer?:
    | T
    | {
        links?:
          | T
          | {
              text?: T;
              url?: T;
              id?: T;
            };
      };
  headContent?:
    | T
    | {
        leading?: T;
        tailing?: T;
      };
  cookieConsent?:
    | T
    | {
        enabled?: T;
        message?: T;
        acceptLabel?: T;
        policyUrl?: T;
        policyLinkText?: T;
      };
  stickyMessage?:
    | T
    | {
        content?: T;
        closeable?: T;
      };
  splashPage?:
    | T
    | {
        enabled?: T;
        centered?: T;
        content?:
          | T
          | {
              contactForm?:
                | T
                | {
                    tallyFormId?: T;
                    id?: T;
                    blockName?: T;
                  };
              contentGrid?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          content?: T;
                          id?: T;
                        };
                    numberOfColumns?: T;
                    horizontalAlignment?: T;
                    verticalAlignment?: T;
                    id?: T;
                    blockName?: T;
                  };
              hero?:
                | T
                | {
                    headline?: T;
                    subheadline?: T;
                    backgroundImage?: T;
                    focalPointY?: T;
                    alignment?: T;
                    height?: T;
                    links?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          variant?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              newsletterSignup?:
                | T
                | {
                    heading?: T;
                    description?: T;
                    buttonLabel?: T;
                    emailPlaceholder?: T;
                    successMessage?: T;
                    mailchimpActionUrl?: T;
                    id?: T;
                    blockName?: T;
                  };
              richText?:
                | T
                | {
                    content?: T;
                    width?: T;
                    renderFloating?: T;
                    floatingOffset?: T;
                    margin?: T;
                    backgroundColor?: T;
                    roundedCorners?: T;
                    id?: T;
                    blockName?: T;
                  };
              spacer?:
                | T
                | {
                    height?: T;
                    id?: T;
                    blockName?: T;
                  };
              splitTextImage?:
                | T
                | {
                    text?: T;
                    buttons?:
                      | T
                      | {
                          caption?: T;
                          link?: T;
                          id?: T;
                        };
                    mediaType?: T;
                    image?: T;
                    focalPointX?: T;
                    focalPointY?: T;
                    vimeoId?: T;
                    videoPoster?: T;
                    videoCtaCaption?: T;
                    imagePosition?: T;
                    imagePercentage?: T;
                    imageSizingMode?: T;
                    imageRatio?: T;
                    imageVerticalMargin?: T;
                    imageHorizontalMargin?: T;
                    imageSize?: T;
                    textContainerMargin?: T;
                    backgroundColor?: T;
                    fullBleed?: T;
                    roundedCorners?: T;
                    collapsedByDefault?: T;
                    startNumberedListAtZero?: T;
                    id?: T;
                    blockName?: T;
                  };
              table?:
                | T
                | {
                    csvData?: T;
                    showBorders?: T;
                    firstRowAreTitles?: T;
                    lastRowAreButtons?: T;
                    buttonLinksCsv?: T;
                    id?: T;
                    blockName?: T;
                  };
              testimonials?:
                | T
                | {
                    testimonials?:
                      | T
                      | {
                          quote?: T;
                          name?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              video?:
                | T
                | {
                    vimeoId?: T;
                    posterImage?: T;
                    ctaCaption?: T;
                    width?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}